local Color, colors, Group, groups, styles = require('colorbuddy').setup()

vim.g.colors_name = 'monokai-soda'
vim.cmd('set background=dark')

-- pallete
Color.new('purple', '#AE81FF')
Color.new('yellow', '#E6DB74')
Color.new('pink', '#f92a72')
Color.new('white', '#cfcfc2')
Color.new('gray', '#75715e')
Color.new('darkgray', '#444444')
Color.new('black', '#222222')
Color.new('blue', '#66d9ef')
Color.new('green', '#a6e22e')
Color.new('orange', '#fd971f')

-- syntax groups
Group.new('Comment',        colors.gray,   colors.none, styles.NONE)
Group.new('Constant',       colors.purple, colors.none, styles.bold)
Group.new('String',         colors.yellow, colors.none, styles.NONE)
Group.new('Character',      colors.yellow, colors.none, styles.None)
Group.new('Number',         colors.purple, colors.none, styles.NONE)
Group.new('Boolean',        colors.purple, colors.none, styles.NONE)
Group.new('Float',          colors.purple, colors.none, styles.NONE)
Group.new('Identifier',     colors.orange, colors.none, styles.NONE)
Group.new('Function',       colors.green,  colors.none, styles.NONE)
Group.new('Statement',      colors.pink,   colors.none, styles.bold)
Group.new('Conditional',    colors.pink,   colors.none, styles.bold)
Group.new('Repeat',         colors.pink,   colors.none, styles.bold)
Group.new('Label',          colors.yellow, colors.none, styles.bold)
Group.new('Operator',       colors.pink,   colors.none, styles.NONE)
Group.new('Keyword',        colors.pink,   colors.none, styles.bold)
Group.new('Exception',      colors.green,  colors.none, styles.bold)
Group.new('PreProc',        colors.green,  colors.none, styles.NONE)
Group.new('Include',        colors.green,  colors.none, styles.NONE)
Group.new('Define',         colors.blue,   colors.none, styles.NONE)
Group.new('Macro',          colors.white,  colors.none, styles.italic)
Group.new('PreCondit',      colors.green,  colors.none, styles.bold)
Group.new('Type',           colors.blue,   colors.none, styles.NONE)
Group.new('StorageClass',   colors.orange, colors.none, styles.italic)
Group.new('Structure',      colors.blue,   colors.none, styles.NONE)
Group.new('Typedef',        colors.blue,   colors.none, styles.NONE)
Group.new('Special',        colors.blue,   colors.none, styles.italic)
Group.new('SpecialChar',    colors.pink,   colors.none, styles.bold)
Group.new('Tag',            colors.pink,   colors.none, styles.italic)
Group.new('Delimiter',      colors.gray,   colors.none, styles.NONE)
Group.new('SpecialComment', colors.gray,   colors.none, styles.bold)
Group.new('Debug',          colors.white,  colors.none, styles.bold)
Group.new('Underlined',     colors.gray,   colors.none, styles.underline)
Group.new('Ignore',         colors.gray,   colors.none, styles.NONE)
Group.new('Error',          colors.black,  colors.orange, styles.NONE)
Group.new('Todo',           colors.white,  colors.black, styles.bold)

-- highlight groups
Group.new('ColorColumn',  colors.none,   colors.darkgray, styles.NONE)
Group.new('Conceal',      colors.white,  colors.none,     styles.NONE)
Group.new('Cursor',       colors.black,  colors.white,    styles.NONE)
Group.new('CursorIM',     colors.black,  colors.white,    styles.NONE)
Group.new('CursorColumn', colors.none,   colors.darkgray, styles.NONE)
Group.new('CursorLine',   colors.none,   colors.none,     styles.NONE)
Group.new('CursorLineNr', colors.orange, colors.none,     styles.NONE)
Group.new('Directory',    colors.green,  colors.none,     styles.bold)
Group.new('DiffAdd',      colors.none,   colors.darkgray, styles.NONE)
Group.new('DiffChange',   colors.gray,   colors.black,    styles.NONE)
Group.new('DiffDelete',   colors.pink,   colors.black,    styles.NONE)
Group.new('DiffText',     colors.none,   colors.darkgray, styles.italic,bold)
Group.new('ErrorMsg',     colors.pink,   colors.black,    styles.bold)
Group.new('VertSplit',    colors.gray,   colors.black,    styles.bold)
Group.new('Folded',       colors.gray,   colors.black,    styles.NONE)
Group.new('FoldColumn',   colors.gray,   colors.black,    styles.NONE)
Group.new('SignColumn',   colors.green,  colors.none,     styles.NONE)
Group.new('IncSearch',    colors.black,  colors.yellow,   styles.NONE)
Group.new('LineNr',       colors.gray,   colors.none,     styles.NONE)
Group.new('MatchParen',   colors.black,  colors.orange,   styles.bold)
Group.new('ModeMsg',      colors.yellow, colors.none,     styles.NONE)
Group.new('MoreMsg',      colors.yellow, colors.none,     styles.NONE)
Group.new('NonText',      colors.gray,   colors.none,     styles.NONE)
Group.new('Normal',       colors.white,  colors.none,     styles.NONE)
Group.new('Pmenu',        colors.none,   colors.black,    styles.NONE)
Group.new('PmenuSel',     colors.none,   colors.darkgray, styles.NONE)
Group.new('PmenuSbar',    colors.none,   colors.darkgray, styles.NONE)
Group.new('PmenuThumb',   colors.none,   colors.none,     styles.NONE)
Group.new('Question',     colors.none,   colors.none,     styles.NONE)
Group.new('Search',       colors.black,  colors.yellow,   styles.NONE)
Group.new('SpecialKey',   colors.gray,   colors.none,     styles.NONE)
Group.new('SpellBad',     colors.none,   colors.orange,     styles.NONE)
Group.new('SpellCap',     colors.none,   colors.purple,   styles.NONE)
Group.new('SpellLocal',   colors.none,   colors.purple,   styles.NONE)
Group.new('SpellRare',    colors.none,   colors.none,     styles.NONE)
Group.new('StatusLine',   colors.white,  colors.darkgray, styles.NONE)
Group.new('StatusLineNC', colors.gray,   colors.black,    styles.NONE)
Group.new('TabLine',      colors.black,  colors.gray,     styles.NONE)
Group.new('TabLineFill',  colors.black,  colors.black,    styles.NONE)
Group.new('TabLineSel',   colors.black,  colors.gray,     styles.NONE)
Group.new('Title',        colors.pink,   colors.none,     styles.NONE)
Group.new('Visual',       colors.none,   colors.darkgray, styles.NONE)
Group.new('VisualNOS',    colors.none,   colors.darkgray, styles.NONE)
Group.new('WarningMsg',   colors.white,  colors.darkgray, styles.bold)
Group.new('WildMenu',     colors.none,   colors.black,    styles.NONE)

-- lsp
Group.new('LspDiagnosticsDefaultError',           colors.orange,   colors.none,      styles.NONE)
Group.new('LspDiagnosticsDefaultWarning',         colors.yellow, colors.none,      styles.NONE)
Group.new('LspDiagnosticsDefaultInformation',     colors.white,   colors.none,     styles.NONE)
Group.new('LspDiagnosticsDefaultHint',            colors.none,  colors.none,       styles.NONE)
Group.new('LspDiagnosticsVirtualTextError',       colors.orange,   colors.none,      styles.NONE)
Group.new('LspDiagnosticsVirtualTextWarning',     colors.yellow, colors.none,      styles.NONE)
Group.new('LspDiagnosticsVirtualTextInformation', colors.white,   colors.none,     styles.NONE)
Group.new('LspDiagnosticsVirtualTextHint',        colors.none,  colors.none,       styles.NONE)
Group.new('LspDiagnosticsUnderlineError',         colors.none,   colors.none,      styles.underline)
Group.new('LspDiagnosticsUnderlineWarning',       colors.none,   colors.none,      styles.underline)
Group.new('LspDiagnosticsUnderlineInformation',   colors.none,   colors.none,      styles.underline)
Group.new('LspDiagnosticsUnderlineHint',          colors.none,   colors.none,      styles.underline)
Group.new('LspDiagnosticsFloatingError',          colors.orange,   colors.darkgray,  styles.underline)
Group.new('LspDiagnosticsFloatingWarning',        colors.yellow, colors.darkgray,  styles.underline)
Group.new('LspDiagnosticsFloatingInformation',    colors.white,   colors.darkgray, styles.underline)
Group.new('LspDiagnosticsFloatingHint',           colors.none,  colors.darkgray,   styles.underline)
Group.new('LspDiagnosticsSignError',              colors.orange,   colors.none,      styles.NONE)
Group.new('LspDiagnosticsSignWarning',            colors.yellow, colors.none,      styles.NONE)
Group.new('LspDiagnosticsSignInformation',        colors.white,   colors.none,     styles.NONE)
Group.new('LspDiagnosticsSignHint',               colors.none,  colors.none,       styles.NONE)

-- plugins
Group.new('ALEErrorSign',         colors.pink,   colors.none, styles.NONE)
Group.new('ALEWarningSign',       colors.yellow, colors.none, styles.NONE)
Group.new('NeomakeErrorSign',     colors.pink,   colors.none, styles.NONE)
Group.new('NeomakeInfoSign',      colors.blue,   colors.none, styles.NONE)
Group.new('NeomakeWarningSign',   colors.yellow, colors.none, styles.NONE)
Group.new('SyntasticErrorSign',   colors.pink,   colors.none, styles.NONE)
Group.new('SyntasticWarningSign', colors.yellow, colors.none, styles.NONE)

-- tree sitter
Group.new('TSAnnotation',         colors.none,   colors.none, styles.NONE)
Group.new('TSAttribute',          colors.none,   colors.none, styles.NONE)
Group.new('TSBoolean',            colors.purple, colors.none, styles.NONE)
Group.new('TSCharacter',          colors.yellow, colors.none, styles.NONE)
Group.new('TSConditional',        colors.pink,   colors.none, styles.NONE)
Group.new('TSConstant',           colors.none,   colors.none, styles.NONE)
Group.new('TSConstBuiltin',       colors.orange, colors.none, styles.NONE)
Group.new('TSConstMacro',         colors.none,   colors.none, styles.italic)
Group.new('TSConstructor',        colors.none,   colors.none, styles.NONE)
Group.new('TSEmphasis',           colors.none,   colors.none, styles.italic)
Group.new('TSError',              colors.none,   colors.none, styles.underline)
Group.new('TSException',          colors.green,  colors.none, styles.bold)
Group.new('TSField',              colors.none,   colors.none, styles.NONE)
Group.new('TSFloat',              colors.purple, colors.none, styles.NONE)
Group.new('TSFunction',           colors.none,   colors.none, styles.NONE)
Group.new('TSFuncBuiltin',        colors.orange, colors.none, styles.NONE)
Group.new('TSFuncMacro',          colors.blue,   colors.none, styles.NONE)
Group.new('TSInclude',            colors.pink,   colors.none, styles.NONE)
Group.new('TSKeyword',            colors.pink,   colors.none, styles.NONE)
Group.new('TSKeywordFunction',    colors.pink,   colors.none, styles.NONE)
Group.new('TSKeywordOperator',    colors.pink,   colors.none, styles.NONE)
Group.new('TSLabel',              colors.yellow, colors.none, styles.bold)
Group.new('TSLiteral',            colors.blue,   colors.none, styles.NONE)
Group.new('TSMethod',             colors.green,  colors.none, styles.NONE)
Group.new('TSNamespace',          colors.pink,   colors.none, styles.NONE)
Group.new('TSNumber',             colors.purple, colors.none, styles.NONE)
Group.new('TSOperator',           colors.pink,   colors.none, styles.NONE)
Group.new('TSParameter',          colors.none,   colors.none, styles.NONE)
Group.new('TSParameterReference', colors.none,   colors.none, styles.NONE)
Group.new('TSProperty',           colors.none,   colors.none, styles.NONE)
Group.new('TSPunctBracket',       colors.none,   colors.none, styles.NONE)
Group.new('TSPunctDelimiter',     colors.none,   colors.none, styles.NONE)
Group.new('TSPunctSpecial',       colors.pink,   colors.none, styles.NONE)
Group.new('TSRepeat',             colors.pink,   colors.none, styles.NONE)
Group.new('TSString',             colors.yellow, colors.none, styles.NONE)
Group.new('TSStringEscape',       colors.purple, colors.none, styles.NONE)
Group.new('TSStringRegex',        colors.yellow, colors.none, styles.NONE)
Group.new('TSStrong',             colors.none,   colors.none, styles.bold)
Group.new('TSStructure',          colors.blue,   colors.none, styles.NONE)
Group.new('TSTag',                colors.pink,   colors.none, styles.NONE)
Group.new('TSTagDelimiter',       colors.gray,   colors.none, styles.NONE)
Group.new('TSText',               colors.none,   colors.none, styles.NONE)
Group.new('TSTitle',              colors.none,   colors.none, styles.NONE)
Group.new('TSType',               colors.none,   colors.none, styles.NONE)
Group.new('TSTypeBuiltin',        colors.blue,   colors.none, styles.NONE)
Group.new('TSUnderline',          colors.blue,   colors.none, styles.underline)
Group.new('TSURI',                colors.none,   colors.none, styles.underline)
Group.new('TSVariable',           colors.none,   colors.none, styles.NONE)
Group.new('TSVariableBuiltin',    colors.orange, colors.none, styles.NONE)
